### ISSUE TITLE
Document cluster monitoring

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#1075]
Minimal User Facing documentation in the quick start guide about existing dashboards and Platform UI cluster status

**Comment by gdemonet** [comment]
Please include a draft of an architecture document for the monitoring stack (in `docs/developer/architecture/monitoring`), and also mention concerns for sizing (e.g. required capacity) and configuration (e.g. retention of time series).

**Comment by gdemonet** [comment]
@thomasdanan what dashboards should we point to in the Quickstart?

@MonPote can you link to/add here some documentation of the Cluster status in the UI (i.e. what indicators are presented, how they can be interpreted)?

**Comment by MonPote** [comment]
We now have a new default page that is called [`Cluster Monitoring`](https://puu.sh/DBv6F/7bbd537ff6.png).

There are 2 types of data on this page :

- The Cluster Status have 2 state :
  - `Everything is up and running` in green  (`apiserver`, `kube-scheduler`, `kube-controller-manager` are all UP)
  - `DOWN` in red (one or more jobs are down)

The exact query to prometheus is `sum(up{job=~"apiserver|kube-scheduler|kube-controller-manager"} == 0)`

- The list of alerts.
Each alert will have a `Name`, a `Severity`, a `Message` (optional) and since when the alert has been created.

**Please note that the polling is not yet implemented. You need to refresh the page to get the latest alerts and status (it will be implemented very soon though).**
