### ISSUE TITLE
Adding a new etcd node failed

### ISSUE THREAD

**Issue by xaf-scality** [scality/metalk8s#1088]
During the installation with the command

`salt-run state.orchestrate metalk8s.orchestrate.deploy_new_node saltenv=metalk8s-2.0 pillar="{'bootstrap_id': 'bootstrap.novalocal', 'node_name': 'pmaster-01.novalocal'}"`
 
we use localhost and not the ip of the server to complete the configuration of the etcd cluster with the new node.
Here is the output of the command:

`----------
          ID: Register the node into etcd cluster
    Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 558, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 263, in _call_function
                  raise error
              CommandExecutionError: etcdctl: client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://localhost:2379 exceeded header timeout
     Started: 13:02:48.085989
    Duration: 4695.9 ms
     Changes:`

**Comment by NicolasT** [comment]
I kinda tried the same scenario this afternoon, and everything completed nicely. Would warrant another attempt using a more recent build?

**Comment by NicolasT** [comment]
BTW, using `localhost` should actually be fine, my mistake.

**Comment by NicolasT** [comment]
Cross-referencing https://github.com/scality/metalk8s/issues/878

**Comment by ramanduh** [comment]
I had a similar issue recently, sometimes the state works and sometimes it doesn't, I did not success to isolate the problem yet, but it may depends on network (it worked at the office, but not at home) or may depends on platform (worked after a `vagrant destroy`, but not after a `snapshot restore`). But it seems that the root cause it that the query was sent to `::1` and we did not listen on the address. We may need to update the `--listen-client-urls` to `--listen-client-urls=https://127.0.0.1:2379,https://172.21.254.3:2379,https://[::1]:2379` or `--listen-client-urls=https://localhost:2379,https://172.21.254.3:2379` in the etcd manifest

**Comment by NicolasT** [comment]
Or use `127.0.0.1` instead of `localhost`? :man_shrugging:

**Comment by NicolasT** [comment]
Now, rather than have whatever work-arounds, can we please tackle #878.
