### ISSUE TITLE
kube-state-metrics pod becomes pending after adding a node from metalk8s-ui

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1201]
**Component**:

salt, metalk8s-ui

**What happened**:

After adding a cp node from metalk8s-ui, the kube-state-metrics pod goes to Pending state

**What was expected**:

kube-state-metrics should remain Running and should be scheduled on all nodes of the cluster

**Steps to reproduce**

DO: deploy metalk8s bootstrap node
OBSERVE: kube-state-metrics pod is in RUNNING state
DO: add and deploy a node from metalk8s-ui
EXPECT: kube-state-metrics is scheduled on the new node and is in running state
OBSERVE: kube-state-metrics is **not** scheduled on the new node and goes to pending state

**Resolution proposal** (optional):

**Comment by gdemonet** [comment]
I don't think it *needs* to be scheduled elsewhere, unless of course there are more than 1 replica running on a previously existing node, and even then I don't know if the behaviour is automatic.

However, it changing state because of a node addition to the cluster is really strange, and worth investigating further.

**Comment by TeddyAndrieux** [comment]
Agree with @gdemonet.

Bug due to https://github.com/kubernetes/autoscaler/issues/188
Upgrade addon-resizer to at least 1.8.3 should fix the issue
