### ISSUE TITLE
Static Pod management tests occasionally fail

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1304]
**Component**: tests, salt

**What happened**:

Multiple occurences of flaky failure, apparently caused by race conditions.

Two symptoms:

- `assert pod.metadata.uid != static_pod_id` fails (the Pod UID did not change)
- `pods "static-pod-<hostname> not found` (the static Pod failed to be created)

**What was expected**: This test should **always** pass.

**Steps to reproduce**: N/A (flaky)

**Resolution proposal** (optional): Ensure timeout/retries are sufficient for having a Pod created, investigate if the unchanged UID is due to race issues (in which case one can increase waiting time) or not.

**Comment by NicolasT** [comment]
+1 in https://eve.devsca.com/github/scality/metalk8s/#/builders/15/builds/2348 (`AssertionError: assert '60987e55-a884-11e9-9c1c-fa163e446080' != '60987e55-a884-11e9-9c1c-fa163e446080'`)

**Comment by NicolasT** [comment]
I wasn't aware of this issue.

This is *likely* fixed by https://github.com/scality/metalk8s/pull/1568, unless the timeout in there is still reached (which *can* happen, but in that case the system must be severely overloaded/malfunctioning).

Pro-actively closing this one, can be reopened if the test turns out to still be flaky.
