### ISSUE TITLE
MetalK8s online documentation from scality.com is completely non-functional

### ISSUE THREAD

**Issue by wabernat** [scality/metalk8s#1357]
Accessing the Scality documentation site at: https://documentation.scality.com/metalk8s.html and clicking the links does not inform me about how to install or use MetalK8s. Clicking PDF buttons produces no result. Clicking the HTML button ("View") for Installing MetalK8s takes me to a ReadTheDocs page at: https://metal-k8s.readthedocs.io/en/latest/installation-guide/index.html. All links on this page are 404. Clicking the View button on the Scality page for access to Operations and Reference take me to RTD 404/maze pages. 

I expected to see useful documentation.

To reproduce: Go to https://documentation.scality.com/metalk8s.html and click anything. 

Resolution proposal: Treat this the same as the rest of our documentation. 

[docs]  If this is not the correct venue for this issue (i.e., it's a releng problem) please advise.

**Comment by NicolasT** [comment]
So, here's what happened: recently, we switched the 'default' documentation view on ReadTheDocs to point to the MetalK8s 2.x documentation (after @GiorgioRegni brought this up), which is also the 'default' branch on Github for some time, so makes sense.

However, it appears that documentation.scality.com links to the 'latest' docs on ReadTheDocs (it's in the URL), not a specific version, which is of course wrong.

Two alternatives:
- documentation.scality.com should host a copy of the MetalK8s docs, as it does for our other projects, and everything is fine
- documentation.scality.com links to ReadTheDocs, not to the 'latest' version, but to the rendering of a particular version/release

I'd prefer the first option: we shouldn't depend on ReadTheDocs for commercial users. In any case, 'latest' is never the right choice if one needs stable URLs.

Assigning to @lucieleonard but closing here, since there's not much the MetalK8s project can do about this. Also CC @smaffulli @dashagurova, and I'll forward the Github email from this ticket internally.

Thanks for reporting!
