### ISSUE TITLE
Store MetalK8s cluster version in an annotation

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1440]
**Component**:

'salt', 'kubernetes'

**Why this is needed**:

To fill version in UI for expansion. #1252 
To use it when downgrading/upgrading

**What should be done**:

Store MetalK8s cluster version during bootstrap 

**Implementation proposal** (strongly recommended):

Store MetalK8s version in an annotation of `kube-system` Namespace in bootstrap script (at the end ?)

**Test plan**:

**Comment by Ebaneck** [comment]
@TeddyAndrieux Can we not populate this annotation directly into the control-plane-manifest(Pod Template) since the namespace is always `kube-system` ??

If we go by adding this to the `bootstrap script`, I assume this will mean patching a deployment.

 The formal looks to me like the cleaner way of doing it??

Let me know what you think??

**Comment by TeddyAndrieux** [comment]
@Ebaneck no you don't want to do it in a deployment.
It's just editing the namespace to add an annotation to this `kube-system` namespace.

You need to create a function in kubernetes module to patch a namespace OR function to list/add/remove annotations from a namespace.

**Comment by NicolasT** [comment]
@TeddyAndrieux is right, this value is a property of the *cluster*, not of a particular Pod/Deployment/..., so setting it on a Namespace that we know will always exist makes sense. `kube-system` instead `default` or `kube-public`.
