### ISSUE TITLE
Get Salt API port from Kubernetes

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1464]
**Component**:

operator

**Why this is needed**:

To be more future-proof: if one day we change the Salt API port in the Salt configuration, we must also update the code of the storage operator: this is error prone.

**What should be done**:

Find a way to retrieve the Salt API port from the Kubernetes API instead of using an hardcoded value.
A possible pointer? => https://kubernetes.io/docs/concepts/services-networking/service/#dns

**Test plan**:

The storage operator should be working as before, no visible impact.

**Comment by Ebaneck** [comment]
@slaperche-scality I think we already have this information present within the external pillars defined and obtained using service endpoints.

I think something like `salt-call --out txt pillar.get metalk8s:endpoints:salt-master:ports:api | cut -c 8-` should yield the salt API port from Kubernetes

**Comment by NicolasT** [comment]
@Ebaneck The operator is Go code running inside the Kubernetes cluster, and shouldn't go through Salt to retrieve this information, it can (and should) connect to the K8s API server.

**Comment by NicolasT** [comment]
In general, I'm not sure there's anything to do here. We *could* consider retrieving the port from a DNS SRV lookup, or retrieve it from the K8s API. However, that would just add another hard-coded name (instead of number) to the lookup code, which is then to be used to retrieve the SaltAPI port from the K8s `Service` (or construct the corresponding DNS SRV query).

The K8s `Service` is a way to abstract access to individual containers, and any ports defined on a `Service` can map to *other* ports on the backing `Pod`s (named ones though, ideally). As such the `Service` (when of type `ClusterIP`) provides a 'stable interface' to access the backing `Pod`s, and can use some well-known port, no need for any lookups.

**Comment by slaperche-scality** [comment]
Yes, if we replace something hard-coded by another hard-coded value, there is no gain.

So let's stay with the current code then.
