### ISSUE TITLE
Prepare volume with Salt

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#1474]
**Component**: salt, storage

**Dependencies**:
- [ ] #1473 

**Why this is needed**: To be able to write persistent data on disks (for Prometheus, Solutions, ...)

**What should be done**: Add Salt formulas to handle the volume creation, for the moment we only want to handle raw & loop devices.
* Check StorageClass validity (ensure that the requested storage class exists and the requested parameters associated to it are set and valid)
* Loop devices (Create the loop device and the sparse file associated to it)
* Create FS on devices (mkfs)
* Mechanism to create automatically loop devices at system start-up

**Implementation proposal**: 
The state should be able to take 1 or 0 device as parameter, if nothing is provided, we must prepare all the volumes not prepared yet.
For loop devices, we can use a systemd unit to ensure their creation at the system start-up, but another solution would be to use some kind of event provided by Salt when minion starts (this solution would be cleaner, we need to be check if it's doable)

**Test plan**: We should be able to prepare a device (a loop and a raw device).

**Comment by NicolasT** [comment]
> Loop devices: sparse file creation (dd)

or `fallocate`, or `truncate`, or (even better) writing a Salt module to do exactly that, create a sparse file, without shelling out.

> Create FS on devices (mkfs)

... with the right FS UUID

> Mount devices (need to check if Kubelet does it by itself)

No need to mount, `kubelet` handles this when the `path` of a `local` PV is a block-device.

> For loop devices, we probably don't need to create the loop device (losetup) as mounting with option "loop" will create it.

That won't work. `kubelet` won't pass that option. And if we'd put `SparseLoopDevice`s in `fstab`, then they could be mounted, the loop device will be created, and `kubelet` *could* then try to mount said loop-device, but because it's already mounted elsewhere, that'... not work too well.

We need to either ensure the loop device gets created at boot/after creation, or implement a CSI driver which can handle sparse file backed filesystems, which we don't have (and would be way too much work, out of scope of this project).

**Comment by NicolasT** [comment]
So, creating the sparse file won't even require custom coding: Salt already has a built-in `truncate(path, length)` procedure in the `file` module which we can use for this purpose:

```python
def truncate(path, length):
    '''
    .. versionadded:: 2014.1.0

    Seek to a position on a file and delete everything after that point

    path
        path to file

    length
        offset into file to truncate

    CLI Example:

    .. code-block:: bash

        salt '*' file.truncate /path/to/file 512
    '''
    path = os.path.expanduser(path)
    with salt.utils.files.fopen(path, 'rb+') as seek_fh:
        seek_fh.truncate(int(length))
```
