### ISSUE TITLE
Check volume name is not already created.

### ISSUE THREAD

**Issue by MonPote** [scality/metalk8s#1495]
**Component**: storage, ui

**Why this is needed**:
We won't allow the user to create a volume with a existing volume name.

**What should be done**:
We should check if the volume `name` enter by the user is already use.
 
**Implementation proposal** (strongly recommended):
- Fetch the list of volume in the form.
- Get the list of volume and check if the volume input is equal to a volume name
- You should use something like 
```javascript
  const volumeListName = ['vol1', 'vol2', 'v3'];
  yup
    .string()
    .test(
      'volume-name-already-exist',
      'The volume name already exist',
      value => !volumeListName.includes(value)
    );

```

**Comment by NicolasT** [comment]
This is a textbook TOCTOU bug/issue, because you'll need to handle names being rejected by the server (due to duplication, or other reasons) anyway. Not only names, also whatever other fields we may at some point either validate through an admission controller, or through the OpenAPI schema.

What I'm aiming at: client-side validation is mostly a waste of effort because TOCTOU, because it's hard to keep checks at the client side in sync with checks at the server side, and you *need* to properly handle server rejections (e.g. validation failures) in your client anyway.

**Comment by MonPote** [comment]
> This is a textbook TOCTOU bug/issue, because you'll need to handle names being rejected by the server (due to duplication, or other reasons) anyway. Not only names, also whatever other fields we may at some point either validate through an admission controller, or through the OpenAPI schema.
> 
> What I'm aiming at: client-side validation is mostly a waste of effort because TOCTOU, because it's hard to keep checks at the client side in sync with checks at the server side, and you _need_ to properly handle server rejections (e.g. validation failures) in your client anyway.

Ok I agree with that. Let close this issue.

**Comment by slaperche-scality** [comment]
The goal of those client-side checks are more about failing early to improve UX (like forbid the creation instead of waiting a backend error that comes after a looooong Salt call).

Clearly, they are not bullet-proof (because of TOCTOU) and you still have to handle errors anyway (in both front-end and back-end).

So it's a balance between how much extra-code is needed VS how much it improves the UX.
Sometimes it's worth it, some it's not.

Maybe in that case it's not and it's fine to close it as won't fix :slightly_smiling_face:
