### ISSUE TITLE
Impossible to delete a volume in status failed

### ISSUE THREAD

**Issue by mcolzi** [scality/metalk8s#1673]
**Component**:
Volume Web GUI management

**What happened**:
I created a volume and the creation has failed. I would like to remove it using the GUI but, first the tips is empty and second when I click on the trash bin nothing happen.

If I list my current pv with kubectl it doesn't appeared in the list. The information seems to be only in the GUI db.

**What was expected**:
Being able to remove it to recreate it with the same name.

**Steps to reproduce**
Create a raw block device with a wrong device name it will fail.

**Resolution proposal** (optional):

**Comment by slaperche-scality** [comment]
If the device path was wrong, the `PersistentVolume` (a.k.a `PV`) wasn't created so it's normal that you don't see it with `kubectl`.
The UI shows `Volume`, not `PersistentVolume`, which would explain the difference.

If you run `kubectl get volume` do you see the `Failed` volume? (normally yes, because both UI and `kubectl` relies on the same DB).

Also, would be interesting to see the logs of the `storage-operator` pod (`kubectl logs -f <POD-NAME>` where `<POD-NAME>` is probably `storage-operator-some-random-string`).

**Comment by mcolzi** [comment]
Yes kubectl get volume lists the 'failed' volume properly
I succeeded to remove it with a kubectl delete volume

**Comment by slaperche-scality** [comment]
Ok, so it was shown both by `kubectl` and the UI, which is good (and expected).

Now, you were able to delete it with `kubectl` so it's probably not a backend bug.

UI is supposed to make the same k8s API call as `kubectl` so it's supposed to works exactly the same. We may have a UI bug here.

**Comment by mcolzi** [comment]
Yes it sound to be a GUI issue. Just create a volume with a bad raw block device, the creation will fail, wihch is expected, and then you can't remove the device through the GUI, which is not expected

**Comment by slaperche-scality** [comment]
Yup, root cause was found, a fix is on its way :slightly_smiling_face:

**Comment by Ebaneck** [comment]
Did we miss this test scenario in the E2E test for Volume Creation/Deletion in the UI?  Would be useful to add test for this.

**Comment by slaperche-scality** [comment]
Yes, unit tests will be added for this one (it's a bug in the logic of the deletion button, so a unit test is enough.)
