### ISSUE TITLE
Volume: Device path is not fullfil properly

### ISSUE THREAD

**Issue by mcolzi** [scality/metalk8s#1705]
**Component**:
Web Gui volume information on a volume that fails to create

**What happened**:
The Path field is empty: may be because we have a device path, because of the RawBlockDevice type.

**What was expected**:
Having the device path in the path field. This could help to investigate. If I ran kubectl describe <MY-VOLUME> I get the device path. So the information exists
```
Spec:
  Node Name:  metal-k8s-servers01.novalocal
  Raw Block Device:
    Device Path:       /dev/vdb1
  Storage Class Name:  zenko
```

**Steps to reproduce**
Create a volume that has RawBlockDeviceType I guess the creation must fail.

**Resolution proposal** (optional):
Get the Device Path when the Type is RawBlockDevice

**Comment by slaperche-scality** [comment]
Hum I may know why it's like that (to be confirmed by front-end people).

The `path` and `capacity` info are fetched from the `PersistentVolume`, not from the `Volume`.
This makes the code simpler because we don't need to juggle between both objects (`Volume` and `PersistentVolume`) to know where to take what:
- for `rawBlockDevice` we have `path` in `Volume` but `capacity` is only in the `PersistentVolume`
- for `sparseLoopDevice` we have the `capacity` but the `path` is only in the `PersistentVolume`.

Since `PersistentVolume` always have both fields we take the info here.
Now in the case of a failed volume, the `PersistentVolume` may not be created and thus we don't have the info.

Maybe we want to have a fallback here (if no `PersistentVolume`, try to get the info from the `Volume`).
