### ISSUE TITLE
Split `solution-manager` script

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#1852]
**Component**: salt, scripts

**Why this is needed**:

Currently, adding a Solution to the cluster using the `solution-manager.sh` script will result in two operations:

- First, mounting the ISO and exposing the container images in the cluster registry
- Then, deploying the highest version of Admin UI / CRDs / ... for a given Solution name

These two actions have different repercussions on the life of the cluster and the applications running on top of it, so having a clear separation is meaningful for end-users.

The second action could be naturally moved into Platform UI as well, in a future iteration (see #1610).

**What should be done**:

Split the Salt formulas / orchestrate runners and the `solution-manager` script to provide:

- `-a/--add ARCHIVE`: mount the archive and expose its images
- `-r/--remove ARCHIVE`: stop exposing the images and unmount the archive
- `--deploy NAME:VERSION`: deploy the singleton components for Solution `NAME` in version `VERSION`

An optional `undeploy` functionality could be interesting, though will wait for a rewrite of the script ~as a `kubectl` plugin~ in Python (see #1854).

**Test plan**:

Include this new approach in tests from #1850

**Comment by NicolasT** [comment]
I don't believe this particular script (or at least not all of its functionality) ought to be implemented as a `kubectl` plugin.

Anything `kubectl` does can *only* go through APIs (in our case, K8s API and SaltAPI), because *it can run on any machine with access to the control plane*, i.e., once we need access to 'local files' on the bootstrap machine, or perform actions local to said machine (e.g., bootstrap/upgrade/downgrade), I don't think how this could work.

I think any `kubectl` plugin we build (ref #1065) should primarily work on K8s objects and not much more, i.e. it could make it easier to add/deploy a new node, change node role(s) (over time), create volumes,...

**Comment by gdemonet** [comment]
> Anything `kubectl` does can _only_ go through APIs (in our case, K8s API and SaltAPI), because _it can run on any machine with access to the control plane_, i.e., once we need access to 'local files' on the bootstrap machine, or perform actions local to said machine (e.g., bootstrap/upgrade/downgrade), I don't think how this could work.

OK, I guess we can split "bootstrap-related" logic from "K8s-related" logic. However, I would argue that `kubectl` is going to be one of the CLI tools to use when managing MetalK8s, so I find it comfortable for the end user to manage other _details_ of MetalK8s with this tool as well.

I agree that semantically, `kubectl` is for K8s objects, not MetalK8s local operations. However, I feel all actions currently performed by this script can be achievable using SaltAPI, except maybe logging.

We still need a rewrite to use a _real_ language though, so let's start with having some `metalctl` entrypoint and discuss about making (part of) it a `kubectl` plugin later.

**Comment by NicolasT** [comment]
I'd rather not end up with a situation where, if one installs the plugin on a local system, some functionality of it doesn't work because you're not executing the thing on the bootstrap node (locally).

In the case of `iso-manager`, granted, everything could run through Salt(API). However, one would need to provide a *local* path on the bootstrap node. Not sure that's a good idea.

Similarly, for bootstrap/upgrade/downgrade, I'm not sure integration in `kubectl` is a good idea: some stages of upgrade/downgrade need to run on the bootstrap node, because we (need to) use 'local' mode of Salt, right? So we'd end up with some 'admin' functionality to be through scripts/a custom CLI tool (#1588) and some other 'admin' functionality would then go through `kubectl` because that happens to be not-strictly-local actions.

**Comment by gdemonet** [comment]
OK, I get the rationale. Bootstrap-local operations should only be available on the bootstrap node(s), to avoid disappointment, and as such, most of the current scripts we have would land in such a CLI entrypoint. Other functionalities that make sense to run from anywhere (given access to K8s and Salt APIs) could land in a `kubectl` plugin.

**Comment by NicolasT** [comment]
Another, more technical reason (for now): when using `kubectl`, one will likely use `admin.conf` or similar, i.e., a *KubeConfig* which uses TLS certificates. We don't support certificate-based auth towards SaltAPI (and I'm not sure how feasible it is to implement this would be), so the 'likely most used' config for `kubectl` wouldn't allow to call into SaltAPI anyway.

**Comment by gdemonet** [comment]
The script is now exposing sufficient subcommands (`import`, `activate`, `create-env`...).

`kubectl` plugin will be tracked in a design for #2163
