### ISSUE TITLE
Calico is not deployed on master-only Nodes

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2380]
**Component**: salt

**What happened**: When deploying Nodes with only the `master` and `etcd` roles, some Pods wouldn't start on said Nodes (namely, the control-plane Ingress controller Pods), due to missing CNI configuration (and indeed, Calico was not deployed).

**What was expected**: Calico should be deployed on all K8s Nodes (only a `ca`-only minion wouldn't need Calico to run).

**Steps to reproduce**: Deploy Nodes with only `master` and `etcd` role labels.

**Resolution proposal** (optional):

Add `metalk8s.kubernetes.cni.calico` to `metalk8s.roles.master` list of includes.

**Comment by NicolasT** [comment]
Sooooo... I'm not sure this is an 'issue' and whether or not the suggested solution is the right one.

Any service which sits on master/etcd-only nodes should
- only be accessible on the host's control-plane IP (unless proven otherwise?)
- not access any services running as PodIPs (as a client)

All of these can work just fine using the fallback CNI configuration we deploy.

The only one I can think of that 'violates' this rule is the control-plane ingress controller, which while being exposed on the control-plane, requires access to PodIPs/Services.

Now.

The way the control-plane Ingress controller is currently deployed ain't great (using an `externalIP`). This should be fixed somehow anyway (basically, your control-plane ingress running on a non-bootstrap node won't even work today). Either by having a specific `portmap` configuration, or by running them in the host network namespace and bind to the (host) control-plane IP only, somehow.

*Alternatively*, we could revisit whether the control-plane ingress controller should actually run on the master/etcd-nodes. Would it make sense to run it on infra nodes (which need to be part of the CNI network) instead? :thinking:

**Comment by gdemonet** [comment]
Oh, thanks for the explanation, I'll open other issues to describe the problems described here and close this one for reference.

**Comment by alexandre-allard** [comment]
Re-opening this issue as we now need Calico on master nodes for fluent-bit.
