### ISSUE TITLE
Set up the style & layout for Volume page

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2505]
**Component**:
 ui

**Why this is needed**:
We would like to adapt the current volume page to the new design with the volume list on the left side and volume panel on the right side, including `volume info/health/alerts/performance`.

**What should be done**:

**Prerequisites: the design file from UX**:
Will work with @Cuervino to clarify the following questions in the design file:
- How the volume page looks like when landing the page
- Where should we display the `Create Volume Form` (either display it on the right side the panel or go for a new page)

Dev implementation:
- Add the link in the detail node page to access the volume page with the filter.
- Add the entry point in the side-bar to access the global volumes.
- We should still keep the tabs (Details/Volumes/Pods) on the node page. And we could access the `volume page` when I click on a certain volume in the volume list.
- Need to decide how to display the breadcrumb
- Remove the VolumeInformation page and move the volume detail data in the Volume Page. 

There are some additional fields, e.g. `Workload Bound` which is missing right now.
There is no direct way to retrieve the data.
What we could do is when the Volume/PV is bound => find the name of the PVC => list all the pods on this node => find which on has the PVC. Then the Pod should be the `Workload Bound`
Note that a Volume/PV can be bound by more than one node (not in our case I think, but we should still handle it)

**Implementation proposal** (strongly recommended):
![image](https://user-images.githubusercontent.com/18453133/82414464-6258e480-9a77-11ea-8271-580717722ade.png)

**Test plan**:
TBD

**Comment by Cuervino** [comment]
About: 
> How the volume page looks like when landing the page

Here is a proposal:
![volumes view test](https://user-images.githubusercontent.com/28654802/80970701-e0807e80-8e1b-11ea-839d-c7316f1676a5.png)
On the right panel, just a notification "No data selected"
About:
> Where should we display the Create Volume Form (either display it on the right side the panel or go for a new page)

I would go for the right side panel, especially if the whole form is short enough, and if there is only 1 step.

**Comment by slaperche-scality** [comment]
In term of wording, I would use `Available` instead of `Unbound`

**Comment by gdemonet** [comment]
> In term of wording, I would use `Available` instead of `Unbound`

Related to this, I found myself trying to reuse an `Available` Volume after it had been previously consumed by another workload. This is because the PVC has been removed (so the Volume isn't bound), but since the `reclaimPolicy` was set to `Retain` in the StorageClass, we still have the underlying PV available (in case we want to extract the data manually).

It is expected behaviour, but from a UI standpoint, showing a different status (e.g. `Released`) could prove useful when one can't bind such a Volume again.

**Comment by Cuervino** [comment]
New proposal
![image](https://user-images.githubusercontent.com/28654802/81117833-1579f780-8f28-11ea-93fb-fd9cd43c90c1.png)

**remarks:**
-The volume table on the left side has a lot of data, it might be needed to remove some of the columns (as the actual node names could be much longer)
-The lack of space prevents to insert nice visualisation inside the table (gauge bar for "Usage").
-The lack of space prevents to display "sorting" icons and "filtering" icons next to the header of the table.
-A tooltip with full "naming" could be displayed on hoovering for header truncated (example of "Storage Cl." for "Storage Class") 

-For Bound/Unbound, could be replaced by icons.

-The "action" at the end of the table would allow an "Edit/Delete".

-Not clear for me how to display a top 10 

-Where to put the bandwidth/latency ? In the "Performances" panel ?

-For the alerts, are the headers ok ? Is the information "Still active" could be relevant ?
-Is the alert acknowledging dealt on this screen, or is it just a link to another screen for acknowledging the alerts ?

-Is "Volume Type" missing ?

**Comment by thomasdanan** [comment]
> New proposal
> ![image](https://user-images.githubusercontent.com/28654802/81117833-1579f780-8f28-11ea-93fb-fd9cd43c90c1.png)
> 
> **remarks:**
> -The volume table on the left side has a lot of data, it might be needed to remove some of the columns (as the actual node names could be much longer)

- I suggest we remove Creation date or at least that we only display day date in the table. We could also change Creation date level with Created label.
- I wonder if we could mix Bound and Status because I see only 3 cases: Failed + Unbound, Available + Unbound and Available + Bound. We could use an icon + tooltip to display this info in the table.
- We are missing the Health of the Volume in the table. This is important.
- I wonder if storage class is mandatory. May be one field we could move to the Volume Info Panel.

> -The lack of space prevents to insert nice visualisation inside the table (gauge bar for "Usage").
> -The lack of space prevents to display "sorting" icons and "filtering" icons next to the header of the table.
> -A tooltip with full "naming" could be displayed on hoovering for header truncated (example of "Storage Cl." for "Storage Class")
> 

Let's apply my suggestions and see what space we have after that. For the sort/filter let's see what @ChengYanJin @MonPote suggest in terms of new table component.

> -For Bound/Unbound, could be replaced by icons.
> 
yes and maybe mix with Status in the table

> -The "action" at the end of the table would allow an "Edit/Delete".
> 
Yes even if today we cannot Edit a Volume, but that would be useful.
By the way. I think it would make more sense to have those actions in the Volume right panel. Also it would free some space in the table ...

> -Not clear for me how to display a top 10
> 
If we have latency info in the table then we could have next to sort and filter the top 10 feature that would sort items on latency column and display the 10 worst/top elements.

Another option would be to build another table, at the bottom of the first one, that always display the Top10 Volumes on Latency criteria.

> -Where to put the bandwidth/latency ? In the "Performances" panel ?

Yes in the Performance Panel, we need to display: Latency, Bandwidth, IOPS and Usage as charts.
> 
> -For the alerts, are the headers ok ? Is the information "Still active" could be relevant ?

In the first iteration, I suggest this alert table will display Active alerts only.
In a second iteration, if we also want to display past alerts, then we should change the header and have 2 columns: Fired Date and Cleared Date

> -Is the alert acknowledging dealt on this screen, or is it just a link to another screen for acknowledging the alerts ?

Don't know about this yet
> 
> -Is "Volume Type" missing ?

So yes in the Info Panel: Volume Type is missing, the POD on which the Volume is bound is missing, as @nloewensen was suggesting we also need the backend disk (or device id).

**Comment by Cuervino** [comment]
**New proposal**

![volumes_view-version-3](https://user-images.githubusercontent.com/28654802/81195182-cda5af80-8fbd-11ea-8423-cb51fb52f994.png)

**What's new:**
- Add & remove columns in the Left-side Volume table 
- Change "Creation date" into "Created" - Change field format into JJ-MM-AA (no hour)
- Add "Health" column, with a colored icon
- Storage class to remove from Left Volume table
- Change "Alert" panel header into "Active Alert"
- Add Volume Type, Workload Bound, Backend disk on Info details panel
- As the Edit Volume action is not possible, it was not added.
A "Delete" button has been added in the Info Panel.
(A confirmation modal should be displayed for avoiding misclicking)
- A dropdown button for different time period selection in the Volume health panel

**Volume Table specifications**
Here are specifications of the left-side Volume table, that can be reviewed.

| # column | GUIi Header name | Full Name                      | Short description                                         | Format of the field                                                                                                | Length            | Aligned | Example 1            |
|----------|------------------|--------------------------------|-----------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------|-------------------|---------|----------------------|
| 1        | Name             | Volume name                    | The name of the volume                                    | alphanumeric                                                                                                       | 40 digits (up to) | Left    | volume-1             |
| 2        | Node             | Node                           | Father node                                               | alphanumeric                                                                                                       | 40 digits (up to) | Left    | node-3               |
| 3        | Usage            | Usage                          | a gauge for showing the usage of the space for the volume | [gauge] + [used space in %age]or [empty]                                                                           | NA                | Center  | [gauge] 55%          |
| 4        | Size             | Size                           | Total size of the volume                                  | [nnn.nn] + [space] + [storage unit]                                                                                | 9 digits (up to)  | Right   | 6.82 PB              |
| 5        | Health           | Current health of the volume   | Current health of the volume                              | [icon] red (critical) / yellow (warning) / green (ok) / [outline] (non applicable)                                 | 1 icon            | Center  | [yellow circle icon] |
| 6        | Status           | Bounding & availibility status | Bounding & availibility status                            | [icon]3 cases:"exclamation" for "Failed + Unbound""unlink" for "Available + Unbound""link" for "Available + Bound" | 1 icon            | Center  | [link icon]          |
| 7        | Created          | Creation date                  | The date of creation of the volume                        | [date] in format [DD-MM-YY]                                                                                        | 8 digits (up to)  | Right   | 21-07-20             |
| 8        | Latency          | Average latency                | Average latency on the last 24 hours                      | [nnn] + [space] + [time unit]                                                                                      | 6 digits (up to)  | Right   | 29 ms                |

Note on the table:

About Status Column (it's a mix between previous Bounding & Status columns), I propose 3 differents icons.
3 cases:
"exclamation" for "Failed + Unbound"
"unlink" for "Available + Unbound"
"link" for "Available + Bound"
We may add colors if necessary. However I would like to avoid confusion with the Volume Health icon.


**Additional data needed**
The goals is to have realistic-looking fake-data to populate the mockup. Especially for the table. (Could be spreadsheets)


**Open questions**
-Should it be an action of "Bounding" directly on this screen ?
-How many lines should be displayed in the letf-side Volume table ? (in general, and for a mockup screen ?)
-How to deal whith the display of multiple active-alerts ? Sorting them by severity level, displaying the first 2 lines, and possibility to scroll down on the "Active Alert" panel level ?

**Comment by nloewensen** [comment]
Not sure I fully understand the status of "Available and bound". To me, something that is "bound" is no longer "available", so perhaps we need to find a better wording.

As for the Delete-button on the right side, it should probably be "red" in order to find it better (is almost "invisible" now and to indicate that this is a dangerous option.

**Comment by ChengYanJin** [comment]
Hello, @Cuervino Great work! I like the updates of the Volume page!

I also have one open question please,
How do we achieve filter&sort the table based on a certain condition? I think the search bar could realize the function of the filter. How about sort?

**Comment by slaperche-scality** [comment]
@Cuervino 

> Change field format into JJ-MM-AA (no hour)

:+1: for removing the time

But for the date format, I find this ambiguous.
US (and others) uses `MM-DD-YY`, French (and others) uses `DD-MM-YY`: users will probably first "parse" the date in their native format, before realizing their mistake.

Best option would be to localize the date format, but another option would be to use ISO format: `YYYY-MM-DD`, as it's less ambiguous (and has the nice property of easy sorting by comparing the string directly, but that's a detail).

---

> Not sure I fully understand the status of "Available and bound". To me, something that is "bound" is no longer "available", so perhaps we need to find a better wording.

Yup, a `bound` volume is no longer available (at least the underlying PV isn't).

**Comment by thomasdanan** [comment]
@Cuervino Wonderful !!!

@ChengYanJin I think the search field will help you to filter on Volume name. But we also need to filter on some other columns of the table like Volume Status, Volume Health, Node. For this, I think the table should provide a per column filter.

@Cuervino About the possible values in the table:
- for size of a Volume, you can consider it is between 10 TB and 100 TB.
- backend disk: /dev/sdb1

> Open questions
-Should it be an action of "Bounding" directly on this screen ?

No, actually it is more when solution components are scheduled that some PV will be claimed and bound: it is automatic and managed by K8s.

> -How many lines should be displayed in the letf-side Volume table ? (in general, and for a mockup screen ?)

On a system, we will have a lot of Volumes, consider that we have around 100 Volumes. Very often the user has the choice to determine how many rows are displayed in the page but I think 20 rows is a good default value.

> -How to deal whith the display of multiple active-alerts ? Sorting them by severity level, displaying the first 2 lines, and possibility to scroll down on the "Active Alert" panel level ?

Yes we sort by Severity and then age. Ideally we can see 5 active alerts in the table and we can scroll down or change page without having to go to the Active Alert dedicated page ...

@slaperche-scality can you help us determine the various possible status of a Volume? From what I understand it is either:

- provisioning failed
- available
- bound (to a workload)

Can we have other status? like *Released* (I guess if it was previously bound by a specific workload and as such you don't want to make it available for other workloads)?

**Comment by slaperche-scality** [comment]
About the volume status.

The `Volume` object itself don't have a status per se, not since https://github.com/scality/metalk8s/issues/1507.

We now have `conditions`, like a `Pod`.
For now we only have the `Ready` condition, that doesn't tell much but the idea is/was to add more fine-grained conditions so that the UI can have more info.
This isn't implemented yet.

That being said, you can infer a "Volume status", and this is what the current UI does (see the function `computeVolumeGlobalStatus` from `ui/src/services/NodeVolumesUtils.js`).
Currently we have:
- Nothing/Unknown (transient, can happen in the short time between the creation of the CR and the first loop of the operator)
- Pending
- Ready
- Failed
- Terminating

At the `PersistentVolume` level, we have [those](https://godoc.org/k8s.io/api/core/v1#PersistentVolumePhase).

Current UI lookup in both `Volume` and `PersistentVolume`, depending on what it needs (`Bound`/`Released` would be found at the `PersistentVolume` level, we haven't duplicated it at the `Volume` level, but we could add a new condition `Bound` in the `Volume`).

**Comment by Cuervino** [comment]
**Here is a new proposal**

![volumes_view-version-4](https://user-images.githubusercontent.com/28654802/81816747-10223b80-952c-11ea-8d73-50ca01fd6ce8.png)


**What's new**

- Addition of Lateral Sidebar (mid-definition, would be reshaped)
- The Main navbar is displayed (for realistic purpose, another topic)
- Population of Volume table with 20 lines with realistic data
- Addition of slider for the Volume table (if display > 20 lines ? _Pagination topic_)
- Addition of slider for the `Active Alert` table (if display >4 lines)
- Change of Date format (thanks @slaperche-scality, I think that YYYY-MM-DD is the best approch)
- The `Delete Volume` button is in red, and moved to another location on the screen
- `Bound` line in info card has been removed (duplicate)
- `Active Alerts` table filled with more realistic data
- The "time period" (`7 days`) can be selected for the `Volume health` card, and for the `Performances` card
- `Performances` graphs renamed, and more realistic
- The Colors are more aligned with CoreUI color palette

Still open questions :
- Alert system - _should be defined as another topic_
- Sorting, and filtering the tables
- Pagination
- Breadcrumb information to validate
- A proper definition for the `Status` icon. However I'm not sure it's changing the current proposal.

**Comment by nloewensen** [comment]
perhaps a dump question, so my apologies ;). Are we able to see the entire "Alert description" on the right hand side, e.g. hovering over the description (would be nice) or extending the column? For a quick view, customers will probably be able to read the entire description easily.
