### ISSUE TITLE
Possibly using kubedb for elasticsearch deployment, similar to prometheus-operator?

### ISSUE THREAD

**Issue by virtuman** [scality/metalk8s#257]
If prometheus is already being deployed using the operator - i'm wondering if operator approach is something that you prefer over direct deployments. There's a project called kubedb, and it would give a few well-built useful operators that could be used throughout the cluster (not only for the cluster deployments) - some of them are more "complete" than others, but for the ease and unified OPs management of infrastructure and the workloads - could be good to have it "unified":
https://kubedb.com/docs/0.8.0/guides/

- Elasticsearch
- Memcached
- MongoDB
- MySQL
- PostgreSQL
- Redis

**Comment by NicolasT** [comment]
We'd like to keep things as 'simple' as possible. As such, for cluster logging, the current Helm charts for Elasticsearch suit our needs, despite some bugs (e.g. https://github.com/helm/charts/issues/7771)

Keep in mind the Elasticsearch cluster as deployed by MetalK8s in the `kube-ops` namespace is only meant to provide MetalK8s' functionality, not as a general-purpose Elasticsearch database provided to other workloads for whichever needs they may have. If one wants to provide 'Elasticsearch as a service' in a cluster, then indeed KubeDB could be viable, but needs to be deployed outside MetalK8s' realm.

Even `prometheus-operator` could be kicked out one day: we mainly use it because of `kube-prometheus` which brings a lot of useful Grafana dashboards 'for free'. If there were an easy way to deploy (and update) these dashboards without requiring `prometheus-operator`, we may go that route.
