### ISSUE TITLE
Test plan for Volume Page

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2681]
**Component**: UI, tests

**Why this is needed**: Following by the work of `Pragmatic Front-End Testing Strategy`, I want to apply the strategy to a real case to make sure the Volume Page works correctly.

**What should be done**:
- Add Unit test for utility functions
- Cypress Interaction test 
- Adapt the current E2E test

**Implementation proposal** (strongly recommended):

- Unit test for Utility Functions 
   -  `addMissingDataPoint()` used by Metrics Chart to maually add the missing data points.
   - `getVolumeListData()` used by VolumeListTable to retrive the data for volume table

   - Delete a Non-deletable volume and check if UI prevents the users to do so. (already exist)
- Interaction test scenarios 
   - Select another volume in the volume list and check if the right-side panel is updated.
   - When the status is unhealthy, there is at least an alert displayed (it can be done later)
   - Create Volume from Node page (New added)
-  E2E test
     - Adapt the current `Create Volume` scenario - Create the volume from volume list 
   - Delete a [deletable volume](https://metal-k8s.readthedocs.io/en/latest/_images/plantuml-a3ccb4a4af5a4de64e5a09288ecb459423a3b813.png), which is just created and check if the volume is realy deleted.( it's too costly to mock up the backend) 

What should be covered in the 1st iteration?
- All the Unit test
- Adapt the current `Create Volume` scenario - Create the volume from volume list 
- Delete volume?

Split the issue with #2696 and #2747

**Comment by MonPote** [comment]
> Delete a deletable volume and check if the volume is realy deleted.( it's too costly if we want to mock up the backend)
> Delete a Non-deletable volume and check if UI prevents the users to do so.

I'm really not sure how do you want to unit test both easily.
Are you sure it's a unit test and not a interaction test ?

> Select another volume in the volume list and check if the right-side panel is updated.

You also need to check that the URL is correct and maybe that the `background-color` [css](https://docs.cypress.io/api/commands/should.html#Yields) too

> When the status is unhealthy, there is at least an alert displayed (it can be done later)

This one is indeed tricky, but can be easily done by interaction test if you have a example for what to expect from prometheus (this the difficult part)

I suggest that you invest some time on the interaction test first (before the unit test), I can help you if you need. You will see that it's not that difficult actually **when you have an example of what the back-end will response to you**.

I was really surprise how good the dev UX is with the interaction test.

**Comment by gdemonet** [comment]
> I suggest that you invest some time on the interaction test first (before the unit test)

Well, depends on what you're trying to test as "an interaction":

- for deletable vs. non-deletable Volumes, the only behaviour we want to check is not interaction, it's making sure that for a given input (a `volume` prop to the `DetailsCard` component), the delete button will (or will not) be shown to the user. Such a check does not bring much value in interaction, because we only care about one component in isolation, not even expecting a user clicking on something.
- deleting a Volume is happening in K8s, via reconciliation: you don't "simply" delete it and remove it from your state, you need to wait for it to transition to a `Terminating`, then `Terminated`, then to being garbage-collected. Instead of mocking this long behaviour, why not just make a true end-to-end test?
- for alerts, what's interesting again is checking the state of the UI depending on the inputs (props), not much interaction there - but since the behaviour of the API is rather simple to mock (just giving static data is enough), it can also be implemented in integration with Cypress

**Comment by ChengYanJin** [comment]
Only remain interaction test. Will cover in issue #2878.
