### ISSUE TITLE
Default "cluster" selected in Grafana etcd dashboard is incorrect (loki-headless)

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2829]
**Component**: salt, prometheus-operator, grafana

**What happened**:
When you go to the etcd dashboard in Grafana, there is a dropdown list to select the etcd cluster, the first element selected by default is `loki-headless` which obviously is not an etcd cluster, so all the charts are empty.
You have to click on the list and select the right cluster `kube-etcd` to make it works.

![Selection_004](https://user-images.githubusercontent.com/31347867/95067627-66269400-0704-11eb-9ecd-8c7711913231.png)

**What was expected**:
When I go to this page, `kube-etcd` is already selected and I don't have non-existing cluster in the list.

**Steps to reproduce**:
Install a 2.6.x, then go to the Grafana etcd dashboard.

**Resolution proposal** (optional):
The issue comes from the query used to get the list of etcd cluster which is:
```
label_values(etcd_server_has_leader, job)
```
The problem is the loki `/metrics` endpoint also exposes an `etcd_server_has_leader` metric.
So, we need to tune the query to only retrieve etcd clusters.
For this, we need to extract the etcd dashboard from prometheus-operator rendered chart as it's already done for some objects we customize (e.g. Prometheus rules).

**Comment by gdemonet** [comment]
This issue relates to https://github.com/grafana/loki/issues/3262

In MetalK8s 2.10+, we introduced a new version of this etcd dashboard, which hides the `cluster` template variable. The aforementioned issue makes the dashboard unusable (because `loki-headless` is selected by default).

We have three options:

- we can drop these metrics from the recording rule
- we can filter out the "loki-headless" cluster from the Grafana dashboard, and re-enable the `cluster` variable
- we can hardcode the "kube-etcd" cluster in the Grafana dashboard
