### ISSUE TITLE
Metalk8s with Vagrant using custom OVA file

### ISSUE THREAD

**Issue by stalin12** [scality/metalk8s#2880]
**Component**:
VirtualBox

**What happened**: I am trying to start the MetalK8s through Vagrant. With the current code there is a file called Vagrantfile which takes care of it. But I want to provide my own OVA file which should be opened after vagrant_up.

**What was expected**: Vagrantfile should have the provision of taking the custom OVA file

**Steps to reproduce**: doit vagrant_up

**Resolution proposal** (optional):

**Comment by NicolasT** [comment]
This is not something we'll likely work on from our side. However, if this functionality is useful to you, feel free to send a patch/PR to implement the feature.

Also, please note `doit vagrant_up` is merely a wrapper around the build process, some SSH key provisioning for the VMs, Vagrant snapshot management and `vagrant up` (see `buildchain/buildchain/vagrant.py`), so you could use Vagrant's CLI directly instead of relying on `doit` targets.

**Comment by NicolasT** [comment]
Closing for now. If this is still an issue for you, @stalin12, please re-open.
