### ISSUE TITLE
Enrich MetalK8s buildchain verbosity/logs

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#3217]
**Component**:

'buildchain'

**Why this is needed**:

When MetalK8s build is failing, it is very hard to understand the cause of the failure because some logs are missing

**What should be done**:

Get all std out/err available
Have timers to measure the time spent in each phase

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by alexandre-allard** [comment]
We have an issue in CI because we use multiple processes and when an action fails in such case, doit does not pass the output (stderr & stdout) of the action to the reporter.

I've opened an issue on doit side to fix this: https://github.com/pydoit/doit/issues/387
It means, for now, we have multiple choices until the issue is fixed and released upstream:
  - we stay with what we have as of today (except few improvements, e.g. timer)
  - we fork doit repository, fix the issue and use this repo to install doit
  - we get rid of multi processes, meaning the build will take more time (~50 minutes instead of 30)

**Comment by alexandre-allard** [comment]
We choose to fork `doit` repository: https://github.com/scality/doit
There is an opened PR: https://github.com/pydoit/doit/pull/388

**Comment by gdemonet** [comment]
PR was merged :tada: 
Should we point to the last commit, or wait for a tag? I personally would vote for the first option, so we can get the fixes in ASAP.
