### ISSUE TITLE
Do not deactivate SSH root login when the remote user used by ansible is root

### ISSUE THREAD

**Issue by ballot-scality** [scality/metalk8s#367]
Ansible-hardening is deactivating the root login by setting
```
PermitRootLogin no
```
However, if the root user is the only user available for SSH, you remove your access to the server.

Adding a check in preflight check with the used user and if root, modify the variable as to no deny complete access would be a nice safety net.

**Comment by NicolasT** [comment]
So, there's #337 which asserts that the remote user is not root. This is, however, currently not included in any released version.

If the solution introduced in #337 is acceptable, I'd prefer to keep it as-is rather than introduce a condition in the playbook and act one way or another depending on it.

Finally, if people feel very strongly against including `ansible-hardening`, we could remove it altogether...

**Comment by thomasdanan** [comment]
not relevant in metalk8s 2.X and won't fix it in metalk8s 1.X, closing the issue
