### ISSUE TITLE
Deploy `salt-master`

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#546]
**Goal**
Create a Salt *state* to deploy a `salt-master` as a container/`Pod` managed by `kubelet` (using a static manifest).

**Dependencies**
- [x] #544 

**Requirements**
- [x] When deploying the *state*, we want to be sure the *new* `salt-master` is running.

**Delivery**
The `salt-master` `Pod` manifest, deployed using a and the Salt *state*.

**Comment by NicolasT** [comment]
The `Pod` in the static manifest to run `salt-master` should:

- [x] Run in the `hostNetwork` (otherwise things won't work)
- [x] `allowPrivilegeEscalation: false`
- [x] Run with a read-only root (`readOnlyRootFilesystem: true`)
- [x] Drop capabilities
- [x] Set all relevant labels, see https://github.com/scality/metalk8s/blob/638e12c9ab0f27f13081c289461290784d17065e/salt/metalk8s/registry/files/registry-pod.yaml.j2 as an example (also for the above points ^^)
- [x] Have a `readiness` and `liveness` probe (TBD either a TCP port check, or a command to run)
- [x] Have relevant `ports` definitions
- Inject the following paths as a `hostPath` volume into the container:

  - [x] `/etc/salt`, `readOnly` (if possible?)
  - [x] `/srv/scality`, `readOnly`
  - [x] `/var/cache/salt`
  - [x] `/var/run/salt`
