### ISSUE TITLE
Provide a way to automatically build/retrieve and images in one location

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#563]
Based on the sources containing the list and versions of all packages and images needed, we need to have a proper way of building/retrieving everything.

It should be automated, reproducible and could work on any computer (laptop, CI worker, etc.).

**Comment by charlesprost** [comment]
> Somewhat related: @nootal Did you consider using `buildah` (more precisely, `buildah bud` and `buildah push ... docker-archive:...`) instead of Docker to build container images? This would reduce the need for any custom setup (i.e. working Docker) on the build system, not require `root`,...

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/issues/554#issuecomment-461364541_

**Comment by charlesprost** [comment]
To download the Docker images from the Internet: https://github.com/containers/skopeo
Test it by adding the archive from skopeo to the containerd local archive folder.

**Comment by NicolasT** [comment]
So, I repeated some of the investigations I did earlier related to the interactions between Docker, Skopeo, `containerd` and others.

There are two ways to import an image from an archive into `containerd`:
- `ctr images load`
- `ctr cri load`

There are also a couple of ways to export an image from a repository:
- `skopeo copy docker:... docker-archive:...` or `skopeo copy docker:... oci-archive:...`
- `docker pull ...; docker save ...`

Now, here's what works and doesn't work:

- `ctr images load` can load an image exported using `skopeo`
- `ctr images load` can load an image exported using `docker save`

- `ctr cri load` can *not* load an image exported using `skopeo` because it has expectations about the input file not met by what `skopeo` generates, though what `skopeo` generates is still compliant with the 'spec' (I believe)
- `ctr cri load` can load images generated using `docker save`

Given this, one would argue

> Then we use `skopeo copy docker:.. docker-archive:...` to generate the packages, followed by `ctr images import ...` of said package, and done!

That would be great, if only it would work. Two issues:

- It requires some arguments to `cri images import` because the Docker archive as generated by `skopeo` doesn't contain metadata referring to the original image name and/or tag, so these need to be provided explicitly.
- For whatever reason, when importing an image using `ctr images import` (using a `skopeo copy` result and the proper invocation options, or `docker save`), this image shows up in `ctr images list`, but it does *not* show up when using the CRI interface (`crictl images`). As such, it appears this imported image can't be used by CRI-managed containers, despite the `containerd` 1.2.0 release-notes claiming otherwise (see also https://github.com/containerd/cri/issues/909)

So, despite using `skopeo copy ...` to be a much better solution to generate artifacts (rather than `docker pull ...; docker save ...`), and `ctr images import` to be more polished than `ctr cri load` (which is deprecated, I believe, and can't support archives that are not generated by `docker save`), we're stuck with `docker pull ...; docker save ...` and `ctr cri load ...`.

What would be *really* neat is if we could use `skopeo` to generate the archives, and also use `skopeo` to ingest such archive in a `containerd` environment. However, I'm not aware of any such mechanism.

**Comment by thomasdanan** [comment]
Created #587 for everything related to packages ... this one being for images only
