### ISSUE TITLE
Make sure nothing is pulled from the outside when installing

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#713]
The ISO should be self-sufficient and contains everything necessary for an offline installation.
Any connection to the outside (internet, proxy cache, etc.) should be forbidden in the CI environments.

However, Vagrant being essentially a development tool, we will not enforce offline mode there (we may add an option to enable it in the future).

**Comment by gdemonet** [comment]
This will need changes to some tests, which rely on having access to Docker Hub for retrieving a `busybox` image. We should replace it with another utility image available offline, as described in #1093

**Comment by gdemonet** [comment]
Since the introduction of #1928, which removed the `base`, `extras` and `updates` repos from our ISO (see dfabb912c1a818856821d334f1e4c44c8e91a1d3), we disabled the egress constraints in CI (see c1fbf76a2c3542a59ced85edb058d96d3b271ff4).

Reopening this issue to make sure we re-enable the "offline mode" in CI.

**Comment by gdemonet** [comment]
Closed by #3151 - note that RHEL tests are still running online, due to a limitation in our infrastructure.
