### ISSUE TITLE
Bootstrap new nodes with salt-minion ASAP

### ISSUE THREAD

**Issue by sayf-eddine-scality** [scality/metalk8s#739]
We need salt minion to be installed in the minion as soon as possible to make use of the salt master orchestration and control, we should rely on salt-ssh for the first configuration and then switch to master-minion mode

----

Depends on:

- [ ] Expose kube-apiserver to salt-master
- [ ] Provide a dynamic roster to salt-master
- [ ] Expose metalk8s repository on the network as a kube service

**Comment by NicolasT** [comment]
The intent is to, indeed, use SaltSSH to deploy a minion on a node after it's registered in the DB (i.e. using a dynamic roster, see e.g. https://github.com/scality/metalk8s/blob/users/nicolast/moonshot/salt/_roster/kubernetes_nodes.py). Once that's done, this minion can be configured (still though SaltSSH) to connect to the master, we can use a `@wheel` module to register its key with the master, and then use master-driven further deployment. So, the SaltSSH step is a one-off, explicitly triggered.

**Comment by jbertran** [comment]
Deliverable: a runner able to bootstrap a new minion on an empty machine for which we have credentials, i.e. with an IP, SSH key and new minion name.

Steps I see so far:

- [ ] Install `salt-ssh` in the master container, currently not installed
- [ ] Add the machine to the roster using "dumb" roster file modification for now
- [ ] Add the salt-ssh master key<sup>1</sup> to the minion using "dumb" SSH
- [ ] Deploy salt-minion using the [preseed method](https://docs.saltstack.com/en/latest/topics/tutorials/preseed_key.html)
- [ ] (optional) some kind of liveness check of the minion at the end of the run

<sup>1</sup>: `salt-ssh` automatically creates a keypair on first use - maybe needs to be bootstrapped.

**Comment by jbertran** [comment]
From further thinking and discussions, it comes out that this ticket has some 'hard' dependencies. As such it's going back on hold until we have them.

- Have an exposed repository service (and registry), and have the credentials for this on salt-master
- Have a design for the initial SSH key addition to the target node, for salt-ssh purposes. #737 suggests Kube annotations
- Have saltified bootstrap (#626) landed so we can reuse and adapt the bootstrap steps for a targeted empty node

The first 2 items require a working salt-kubeapi communication channel. Since that is a big requirement for other issues as well, I believe we should prioritize it.

**Comment by NicolasT** [comment]
> Have a design for the initial SSH key addition to the target node, for salt-ssh purposes. #737 suggests Kube annotations

Only SSH public keys can be a node annotation, which doesn't necessarily makes much sense because then we'd still require to know the private key somehow.

For SSH to function within a runner, we can have a custom roster which retrieves remote information from annotations on node objects (see https://github.com/scality/metalk8s/blob/users/nicolast/moonshot/salt/_roster/kubernetes_nodes.py for a PoC, though annotations should be namespaced and such), but the keypairs must be pre-provisioned out-of-band.

**Comment by NicolasT** [comment]
> The first 2 items require a working salt-kubeapi communication channel. Since that is a big requirement for other issues as well, I believe we should prioritize it.

I have a small patch to install `python2-kubernetes-client` in the `salt-master` image, which works fine. However, this still requires to somehow bound-mount (`hostPath` volume) a `kubeconfig` file into the `salt-master` container which can then be used to configure access to the API-server. This `kubeconfig` file needs to be generated on the host (though we could initially use `admin.conf` and not have a specific user/role for `salt-master`, which then becomes a debt ticket), which raises the question of when/where this fits in the whole deployment scheme.

**Comment by jbertran** [comment]
> a custom roster which retrieves remote information from annotations on node objects

To me a simple comparison between roster nodes (equivalent to cluster nodes if we just list nodes) and registered salt minions should be sufficient for the scope of initializing the master/minion channel. After this bootstrap, the minion is free to bring itself up to the state required by annotations on itself - i.e. work plane or control plane, specific services offered...

**Comment by charlesprost** [comment]
So just to make it clear, here are the steps for this ticket:

- [x] Make the `make vagrantup` command build a new SSH key pair that will be shared with the bootstrap node (do not use the SSH key pair created by Vagrant) / need to think about how to do it in the CI also
- [x] Make the salt-master have access to this SSH private key from the boostrap node (should be already in place if the /etc/metalk8s is shared with the salt master container)
- [x] Make the salt-master have access to the `salt-ssh` command (maybe it's already done)
- [x] Make the salt-master have access to the Kube API pod manifest (currently hardcoded in the roster, see below)
- [x] Make the salt-master have access to the python kubernetes client (cherry pick this commit https://github.com/scality/metalk8s/pull/760/commits/92fa1a1bd7cf15c94b486cff3ca011a2c8691888)
- [x] Make sure the salt-master is reachable from outside the bootstrap node (otherwise the salt-minion won't be able to reach it)
- [x] Make a manual query in the Kube API server to add a new node with enough information (except the SSH private key) to be able to SSH into it (so hostname/IP/user/port) and use the proper namespace `metalk8s.scality.com` in the annotations (maybe related to #737 )
- [x] Have a roster able to query this information from Kube API server (use this one https://github.com/scality/metalk8s/blob/users/nicolast/moonshot/salt/_roster/kubernetes_nodes.py)
- [x] Manually deploy the SSH public key in the new node authorized keys list
- [ ] Have a runner using this information and the shared private key to connect to the new node, setup repositories, and install salt-minion
  - [ ] We need generic salt states so they can work both for bootstrap node and a new node
  - [ ] We need for the bootstrap minion to add its control plane ip in the mine so other minions can use it

Will be followed by:

- #744 
- #735 
- #738
