### ISSUE TITLE
Error management

### ISSUE THREAD

**Issue by carlito-scality** [scality/metalk8s#774]
-API call error management? interceptor?!
-Form error management (ie NodeCreateForm)
-I18n: how to translate error messages?

-https://github.com/scality/metalk8s/issues/1185

**Comment by gdemonet** [comment]
A global Redux middleware for handling uncaught errors is IMHO a dangerous idea. We tried that pattern in SRW and got nothing good out of it, except that we had a hard time controlling the UI flow in such situations (since the middleware caught the exceptions, the calling component could not inspect them at will).

Notifications, e.g. using [snackbars](https://material.io/design/components/snackbars.html), are a neat feature, but it shouldn't be the de-facto solution for managing API errors.
However, providing generic reducer functions for handling and pre-processing `<ACTION>_ERROR` actions in Redux could be worth a try, in helping to provide a standard for components willing to manage the errors themselves (particularly crucial for form-based components).

**Comment by thomasdanan** [comment]
incmuded in https://github.com/scality/metalk8s/issues/2803
