### ISSUE TITLE
Launch E2E tests in CI

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#781]
Needs #717 

E2E tests are currently available for Vagrant environment through a `tox` manual command.

We want to have them automatically executed on the `single-node` and `multiple-nodes` steps of the CI as part of the pre-merge tests.

Success is defined by having those tests executed in every build in the CI.

**Comment by gdemonet** [comment]
Initial working PR (#844) will be merged as-is, improvements will come in a separate PR (#855).

Changes requested by @nootal:
- [x] Change single-node hostname in `requirements.sh` instead of `eve/main.yaml`
- [x] Rename task for tests execution in single-node stage
- [x] Remove unnecessary double-quotes in `eve/main.yaml`

Changes requested by @slaperche-scality:
- [x] `s/Shell files and templates/Shell scripts/` in `tox.ini`
- [x] Use explicit encoding when writing/reading files (kubeconfig)
- [x] Use more explicit check for single element lists
- [x] Factorize "retry `n` times" pattern

**Comment by gdemonet** [comment]
Closed by #844 and #855
