### ISSUE TITLE
Concurrent `make` fails on repository metadata generation

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#785]
When running `make -j3` or similar, sometimes a bootstrap fails when trying to install `salt-minion`, claiming the package doesn't exist. However, the RPM file is present in the ISO. This could indicate the repository metadata (`createrepo` invocation) is created before all packages are fetched, i.e. a race.

I didn't really investigate this thoroughly, though it seems a sensible explanation.

In any case, reviewing the deps and `make` rules would make sense.

**Comment by slaperche-scality** [comment]
I noticed several "weird" things while porting the Makefile to `doit` (like `package-build-container` depending on `entrypoint.sh` (useless because `entrypoint.sh` is not included in the image) but not on `yum_repositories/*.repo` which is ADDed in the images)

As for the bug you noticed, if I read the Makefile correctly the target that builds the repomd.xml only depends on the build container (so the downloading the packages is not a pre-requisites).

It's easy to fix this in `doit` because you can have task dependencies in addition to file dependencies (that's how I fixed it)¹.

As for make, maybe we can hack around by touching a file when downloading the packages (or maybe there is some cleaner way), packaging guys may know more about that.

----
¹: will be pushed tomorrow morning, I got preempted today and wasn't able to finalize the PR

**Comment by NicolasT** [comment]
I know how to fix it in `make` ;-) However, if your rewrite is almost ready for prime-time, then I may not spend time on this (I guess most people run sequential `make` anyway, otherwise others would've raised this before).

**Comment by slaperche-scality** [comment]
Fixed as a side-effect of https://github.com/scality/metalk8s/issues/708.
