### ISSUE TITLE
Do not overwrite existing Salt environments when configuring Salt master

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#800]
Currently, the `metalk8s.salt.master.configured` state manages a single master configuration file, located under `/etc/salt/master.d/99-metalk8s.conf`, and containing the following declarations:

```
file_roots:
  {{ saltenv }}:
    - {{ iso_root_path }}/salt
pillar_roots:
  {{ saltenv }}:
    - {{ iso_root_path }}/pillar

[...]
```

However, in some scenario where we need to upgrade the Salt master, applying `metalk8s.salt.master.configured` with a new environment will overwrite the previous one, which is not what we want.

A quick solution could be to define a common configuration file which the latest Salt environment could overwrite, and a specific configuration file per environment (could include the MetalK8s version in its name) to define the `file_` and `pillar_roots`.

**Comment by slaperche-scality** [comment]
So, IIUC the idea is to split `/etc/salt/master.d/99-metalk8s.conf` into two files:
- one, `/etc/salt/master.d/99-metalk8s.conf`, that would contains the version-agnostic settings (such as `ext_pillar`, `roster_defaults`, …)
- one, `/etc/salt/master.d/99-metalk8s-$SHORT_VERSION.conf`, that would contains version-dependant settings (`file_roots` and `pillar_roots`).

To do so, we need to:
- remove the version-specific settings from `salt/metalk8s/salt/master/files/master_99-metalk8s.conf.j2`
- add a new template for the version-specific settings
- generate a file from this template in `salt/metalk8s/salt/master/configured.sls`

**Comment by slaperche-scality** [comment]
Ok, after some tests it seems like config files are not merged as we expected, thus this approach doesn't work.

Let's follow @TeddyAndrieux's suggestion and:
- keep generating a single file: `/etc/salt/master.d/99-metalk8s.conf`
- generate it by using `file.serialize` (with `merge_if_exists` set to `true`) instead of `file.managed`).
- get rid of the now unused `salt/metalk8s/salt/master/files/master_99-metalk8s.conf.j2`
