### ISSUE TITLE
Add automated test for node addition

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#982]
We need to add some test about cluster expansions (workload and control plane)

This test should be able to run in the CI

**Comment by TeddyAndrieux** [comment]
Need this one first #1017

**Comment by slaperche-scality** [comment]
To be done:

- create a new subdirectory for those tests: `tests/install`
- implement steps to run the required command:
  - "when I deploy salt minion on node1"
  - "when I install the worker plane on node 1"
  - …
- implement steps to check the success of the expansion:
  - "then the etcd cluster is healthy"
  - "then the etcd cluster has 2 nodes"
  - …
- use thoses steps to create a test scenario for cluster expansion.

**Comment by NicolasT** [comment]
- `tests/install` would be confusing, because we already have tests that run the (bootstrap) `install`.
- There's no more separation between `deploy minion`, `install worker plane`,... soon'ish (#1019 @TeddyAndrieux )
- Please make sure not to land this in one shot/PR. Once there's a test to add a (worker) node to the cluster, that can be integrated. Another test/suite to add a control-plane node can come next. Extending the `etcd` cluster can come after that, etc.

**Comment by slaperche-scality** [comment]
> `tests/install` would be confusing, because we already have tests that run the (bootstrap) `install`.

Indeed.
What could be a better name then?
`tests/multinodes` (since the expansion tests require a multi-nodes environment)?

> There's no more separation between `deploy minion`, `install worker plane`,... soon'ish (#1019 @TeddyAndrieux )

Hope [this document](https://docs.google.com/document/d/1GAMbSTIFhCypBUITg_SunCOeoMdbEfBK_XZZJIw3Wdw/edit) will be updated then (or is there another one that supersedes it?)

**Comment by NicolasT** [comment]
Since #1031 won't land soon apparently, do we move this to *alpha4*? @slaperche-scality @gdemonet @thomasdanan @nootal
